<?php

function notify($to, $data)
{

    $api_key = "SERVER_KEY"; // Cloud message Server key Token

    $url = "https://fcm.googleapis.com/fcm/send";
    $fields = json_encode(array('to' => $to, 'notification' => $data));

    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/

    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, ($fields));

    $headers = array();
    $headers[] = 'Authorization: key='.$api_key;
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
}

$to = "ek3b5dGLTEiu-9Tuv2m-B5:APA91bEEsn31jezgXJNd0UgZYcQhGM_gpA9kANtfS1f6MK1GbdrtFpA_YCpK30WEQT0R_ZNNjyyPxRe7Zzjm3viJOURq1aPd55GCcQSWiNP7kS157PXE7zN04q61WuZEuzCXko41mcTW";
$data = array(
    'title' => 'From Faruq',
    'body' => 'Hi, From PHP Script'
);

notify($to,$data);
echo "Notification Sent";
